In [19]:
import pandas as pd
data={
    "name":("Mohamed","Tamer","Mohamed","Ahmed","Gafaar"),
    "age":(12,323,54,32,52),
"score":(100,None,90,12,12)
}

In [20]:
df=pd.DataFrame(data)

In [21]:
df.describe()

              age       score
count    5.000000    4.000000
mean    94.600000   53.500000
std    128.813043   48.093659
min     12.000000   12.000000
25%     32.000000   12.000000
50%     52.000000   51.000000
75%     54.000000   92.500000
max    323.000000  100.000000

In [22]:
df.describe(include="object")

           name
count         5
unique        4
top     Mohamed
freq          2

In [23]:
df.isnull()

    name    age  score
0  False  False  False
1  False  False   True
2  False  False  False
3  False  False  False
4  False  False  False

In [24]:
df.isnull().sum()

name     0
age      0
score    1
dtype: int64

In [25]:
df.iloc[2]

name     Mohamed
age           54
score       90.0
Name: 2, dtype: object

In [26]:
df.loc[1:2]

      name  age  score
1    Tamer  323    NaN
2  Mohamed   54   90.0

In [27]:
df.loc[2,"score"]=100

In [28]:
df

      name  age  score
0  Mohamed   12  100.0
1    Tamer  323    NaN
2  Mohamed   54  100.0
3    Ahmed   32   12.0
4   Gafaar   52   12.0

In [29]:
len(df)

5

In [30]:
df['age'].value_counts()

age
12     1
323    1
54     1
32     1
52     1
Name: count, dtype: int64

In [31]:
df.head(2)

      name  age  score
0  Mohamed   12  100.0
1    Tamer  323    NaN

In [33]:
def score_average(column):
    
    return df['score'].mean()

In [34]:
df["score"] = df["score"].fillna(score_average(df["score"]))

In [35]:
df["score"]

0    100.0
1     56.0
2    100.0
3     12.0
4     12.0
Name: score, dtype: float64

In [36]:
df

      name  age  score
0  Mohamed   12  100.0
1    Tamer  323   56.0
2  Mohamed   54  100.0
3    Ahmed   32   12.0
4   Gafaar   52   12.0

In [37]:
df.skew

<bound method DataFrame.skew of       name  age  score
0  Mohamed   12  100.0
1    Tamer  323   56.0
2  Mohamed   54  100.0
3    Ahmed   32   12.0
4   Gafaar   52   12.0>